import type { Metadata } from "next";
import { Pirata_One } from "next/font/google";
import "./globals.css";

const pirate = Pirata_One({ weight: "400", preload: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pirate.className}>{children}</body>
    </html>
  );
}
